as yet unclassified
aboutPage
	^aboutPage ifNil: [
		aboutPage := (PRPage named: 'about')
					title: 'About';
					contents: '!The Like Minds Network

The Like Minds project was bourne from the proliferation of social networks that are either single focused, or totally strip users of the rights to their own ideas. Although the "face-spaces" of this world are technically "legal", finding a lawful (and for that matter ethical) network can prove difficult. With the self proclaimed "authorities" all but declaring war on us - the free and living people - there has never been a better time for a network where the wise can share views and ideas, with privacy and security. The Like Minds project ever strives to meet these ideals, and promote intellectual enlightenment.

That said, Like Minds will not appeal to (and to some extent, not tolerate) those committed to promoting ignorance.  It''s said that a mind is like a parachute - it only works when it is open. If you have closed your mind to wisdom and knowledge, you''re unlikely to find what you''re looking for here. Buy a magazine, watch tv, go to church, or become a lawyer - there you will find myriad mindlessness.

!A Professional, Intellectual, and Social Network all in One

Like Minds is fast growing into a Global Community of Thinkers, each with their "own patch of grass" where they can securly publish and share ideas with other "Like Minds". Every one of us committed to searching for the nature of things - never satisfied with a static, dogmatic "truth".

!Ideas into Action - The Ideal Strategy for Successful Projects

Like Minds provides a comprehensive collaboration environment combined with an emerging methodology for the development of ideas that is proving to be the key to "outrageously successful projects."'
	]