as yet unclassified
perspectivesPage
	^(PRPage named: 'perspectives')
		title: 'Perspectives';
		contents: '!Our Perspectives Define Us

We all consider ourselves from different perspectives. When we''re at work, we consider our thoughts and actions from a professional perspective. When with friends, a more social and maybe playful perspective. Sometimes we want to protect our privacy and only share some information with good friends. Sometimes we want to advertise ourselves to the community at large. Either way, Like Minds allows us to portray ouselves appropriately from various perspectives, and gives us complete control over our privacy, our information, and who we choose to share with.

+/system/components/perspectiveWidget+'