as yet unclassified
rootPage
	^rootPage ifNil: [
		rootPage := (PRPage named: 'LikeMinds')
		title: 'Home'.
		rootPage contents: '!Welcome To Like Minds - Bringing amazing people together

Like Minds is bringing great minds together to help move ideas from dreams to reality. If you have a great idea, or want to help develop great ideas, then you have come to the right place.

Like Minds was designed to aid in projects that lead us closer "Towards a Free World". Free of censorship, slavery, scarcity of resources, and waste.

!How Does It Work?

Like Minds starts with collaboration. As with other social networks, Like Minds allows you to find people with similar ideas and passions, communicate with them in a number of ways, and share information and ideas with each other. It does this securly, and privately without diminishing the rights of individuals.

Once you''ve established a group of like minds, you can start to develop your ideas using the Like Minds system to aid in project development, scheduling and process management. The goal is to help realise dreams through a flexible and adaptable project development methodology that is proving to result in "outrageously successful projects".


'.
		rootPage
	]