as yet unclassified
style
	^'
.perspectiveTree .treeReport td .indent {
	height: auto;
}

.perspectiveTree .treeReport td .indent .text {
	height: auto;
}

.perspectiveImage {
	position: relative;
	height: 86px;
	overflow: hidden;
	background-image: -webkit-gradient(linear, left top, left bottom, from(white), to(gray),color-stop(0.3, #ddd));
}

.perspectiveInformation {
	float: left;
	white-space: normal;
}

.perspectiveInformation h1, .perspectiveInformation p {
	margin-bottom: 0px;
}

.contextFieldsEditor {
	padding: 1.5em;
}

.contextFieldsEditor table {
	margin-bottom: 0px;
}

.contextFieldsEditor dt {
	clear: left;
	width: 150px;
	float: left;
	margin-top: 5px;
	background-image: -webkit-gradient(linear, left top, left bottom, from(#eee), to(#ccc),color-stop(0.3, #ddd));
}

.contextFieldsEditor dd {
	float: left;
	width: 400px;
}

dt.isVisible {
	visibility:hidden;
}


'