as yet unclassified
style
	^'
.likeMindsWindow .suWindow {
	background:#e0e0e0;
	border:1px solid #888;
	overflow:hidden;
	position:fixed;
	-moz-border-radius:5px;
	border-radius:5px
}

.likeMindsWindow .suWindow .container {
	overflow:auto;
	padding:2px
}

.likeMindsWindow .label {
	font-weight: bold;
}

.likeMindsWindow .suWindow .title {
	cursor:move;
	background:#888;
	color:white;
	height:20px;
	padding:2px 2px 3px 3px
}

.likeMindsWindow .suWindow .title a {
	text-decoration:none;
	padding:0px;
	cursor: pointer;
}

.likeMindsWindow td {
	padding: 0px;
}
'